# Generated by Django 5.1.1 on 2024-10-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria'),
        ('post', '0002_rename_nombre_categoria_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
