# Generated by Django 5.1.1 on 2024-10-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
